module.exports = {

	PLAYER_ONE_TURN: 0,
	PLAYER_ONE_TURN_READABLE: 'PLAYER_ONE_TURN',
	PLAYER_TWO_TURN: 1,
	PLAYER_TWO_TURN_READABLE: 'PLAYER_TWO_TURN',

	GAME_OFFERED: 'GAME_OFFERED',
	GAME_ACTIVE: 'GAME_ACTIVE',
	GAME_ERROR: 'GAME_ERROR',
	GAME_TIMED_OUT: 'GAME_TIMED_OUT',
	GAME_FINISHED: 'GAME_FINISHED',
	GAME_TO_DELETE: 'GAME_TO_DELETE',

	PLAYER_BOT: 0,
	PLAYER_HUMAN: 1,

	TOKEN_EMPTY: '0',
	TOKEN_EMPTY_READABLE: 'TOKEN_EMPTY',
	TOKEN_PLAYER_ONE: '1',
	TOKEN_PLAYER_ONE_READABLE: 'TOKEN_PLAYER_ONE',
	TOKEN_PLAYER_TWO: '2',
	TOKEN_PLAYER_TWO_READABLE: 'TOKEN_PLAYER_TWO',

	NO_ID: -1,

	GAME_PHASE_1: 0,
	GAME_PHASE_2: 1,
	GAME_PHASE_3: 2,
	GAME_PHASE_WON: 3,
	GAME_PHASE_LOST: 4

};